### ISSUE TITLE
Error in running the training script

### ISSUE THREAD

**Issue by hmhm1190** [allenai/scirepeval#48]
I am running the training script using: 
`python pl_training.py --gpu 1 --ctrl-tokens --tasks-config sample_data/tasks_config.json bert-base-uncased exp1`

But after running one iteration(not sure if iteration is complete), Fstimeout error shows up. Is it because of my timeout settings; Where can I change the timeout settings?
**ERROR: raise fstimeouterror from return_result fsspec.exceptions.fstimeouterror**

Please help

**Comment by hmhm1190** [comment]
I have changed the batch_size to 4 and only running 2 classififcation taks.

**Comment by shruti-singh** [comment]
Hello Amanpreet @amanpreet692 

It seems like I am running into a similar issue. For me, it seems like an issue in loading the data as I see this in my logs:
`fsspec.exceptions.FSTimeoutError: Caught FSTimeoutError in DataLoader worker process 1.`

I am also attaching the error trace. Could you please help in figuring out the issue?
[error_logs.txt](https://github.com/allenai/scirepeval/files/11642953/error_logs.txt)

Thank you!

**Comment by amanpreet692** [comment]
Hello again,
The issue seems to be caused due to server disconnection from AWS s3.
SciRepEval datasets are streamed line by line from s3 using the datasets library, but keeping the connection alive for a long time looks to be causing the problem
We are still investigating how best to get around this issue.

Meanwhile as a work around, please try the following:
i) Using HugingFace datsets:
--> Update datasets library to version ``2.7.1``
--> Checkout the code from this [branch](https://github.com/allenai/scirepeval/tree/amanpreet692-patch-1). The retry count and interval configs have been increased.

ii) Get the datasets locally from AWS S3 (definitely works):
--> Follow these [steps](https://github.com/allenai/scirepeval#aws-s3-via-cli)
--> Change the ``dataset`` property in training/sample_data/tasks_config.json to ``data_files`` as in below:
```json
[
 {
     "name": "fos",
     "type": "classification",
     "multi_label": true,
     "data_files":
     {
         "train": "<scirepeval_data_dir>/train/fos/train.jsonl",
         "dev": "<scirepeval_data_dir>/train/fos/val.jsonl"
     },
     "labels": "sample_data/fos_labels.txt",
     "labels_field": "labels_text",
     "ctrl_token": "[CLF]",
     "sample_size":
     {
         "train": 600000,
         "dev": 40000
     }
 }
]
```
Hopefully this helps. Please let us know if there are any questions!

**Comment by hmhm1190** [comment]
Thanks, Its working now.
