### ISSUE TITLE
corpus_id and doc_id – where do they come from?

### ISSUE THREAD

**Issue by sa-aguilarv** [allenai/scirepeval#54]
Hello! 

Regardless of the task, all meta datasets have `corpus_id` and `doc_id`. Could you please tell me from where you retrieved such data? Or did you generate those IDs?

Thank you in advance for your assistance.

**Comment by amanpreet692** [comment]
Apologies for the late response! `corpus_id` is the semantic scholar identifier for a paper eg. On https://www.semanticscholar.org/paper/BERT%3A-Pre-training-of-Deep-Bidirectional-for-Devlin-Chang/df2b0e26d0599ce3e70df8a9da02e51594e0e992 if you search for corpus id you will find `52967399`. If `corpus_id` is present for a paper it should match to the `doc_id`, but since not all data points in SciRepEval are papers eg. text queries in Search, for a unique identifier you can rely on `doc_id`.

**Comment by sa-aguilarv** [comment]
I understand and was able to query the metadata. Thank you!
